import { SHAPE_FRUIT_MAP } from './fruit.js';
import { BRANCH_MIRRORING } from './tree_config_enums.js';
import type { TreeConfig } from './tree_config.js';
import { TREE_SHAPES, type TreeShape } from './tree_shapes.js';

type ShapeDefaultsRequired = 'fruitType' | 'blobCloseness';

type ShapeDefaultsExcluded = 'stage' | 'shape' | 'seed' | 'customBlobs';

type ShapeDefaults = Pick<TreeConfig, ShapeDefaultsRequired> &
	Partial<Omit<TreeConfig, ShapeDefaultsRequired | ShapeDefaultsExcluded>>;

/**
 * Per-shape defaults from .mpx/REQUIREMENTS.md §3.7. `custom` is intentionally
 * excluded — the custom editor retains whatever the user has configured.
 */
export const SHAPE_DEFAULTS = {
	[TREE_SHAPES.oak]: {
		trunkTwist: 35,
		blobSizeVariance: 2.5,
		blobCloseness: 45,
		trunkSegments: 5,
		trunkCrookedness: 15,
		fruitType: SHAPE_FRUIT_MAP.oak,
	},
	[TREE_SHAPES.pine]: {
		branchDepth: 0,
		branchesLevel1Range: [0, 0] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchMirroring: BRANCH_MIRRORING.off,
		trunkTwist: 20,
		blobCloseness: 60,
		canopyLightColor: '#4a9e5c',
		canopyDarkColor: '#0d2b1a',
		trunkHue: 20,
		trunkSaturation: 45,
		trunkLightness: 20,
		fruitType: SHAPE_FRUIT_MAP.pine,
	},
	[TREE_SHAPES.birch]: {
		blobCount: 6,
		branchesLevel1Range: [1, 2] as readonly [number, number],
		branchAngle: 60,
		blobSizeVariance: 2.5,
		blobCloseness: 35,
		branchThickness: 80,
		trunkSegments: 4,
		canopyLightColor: '#b8e065',
		canopyDarkColor: '#2d5e3a',
		trunkHue: 40,
		trunkSaturation: 8,
		trunkLightness: 82,
		fruitType: SHAPE_FRUIT_MAP.birch,
	},
	[TREE_SHAPES.fir]: {
		blobCount: 6,
		branchDepth: 0,
		branchesLevel1Range: [0, 0] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchMirroring: BRANCH_MIRRORING.off,
		trunkTwist: 20,
		blobSizeVariance: 2.5,
		blobCloseness: 45,
		canopyLightColor: '#3d8b50',
		canopyDarkColor: '#0a2418',
		trunkHue: 22,
		trunkLightness: 28,
		fruitType: SHAPE_FRUIT_MAP.fir,
	},
	[TREE_SHAPES.maple]: {
		branchesLevel1Range: [3, 5] as readonly [number, number],
		branchAngle: 40,
		trunkTwist: 30,
		blobSizeVariance: 1.3,
		blobCloseness: 40,
		trunkSegments: 7,
		trunkCrookedness: 20,
		canopyLightColor: '#e8a028',
		canopyDarkColor: '#8b2010',
		trunkHue: 30,
		trunkSaturation: 20,
		trunkLightness: 35,
		fruitType: SHAPE_FRUIT_MAP.maple,
	},
	[TREE_SHAPES.willow]: {
		blobCount: 6,
		branchesLevel1Range: [3, 5] as readonly [number, number],
		branchAngle: 15,
		trunkTwist: 35,
		blobCloseness: 35,
		branchThickness: 80,
		trunkSegments: 7,
		trunkCrookedness: 20,
		canopyLightColor: '#7cc45a',
		canopyDarkColor: '#1a4020',
		trunkSaturation: 40,
		trunkLightness: 22,
		fruitType: SHAPE_FRUIT_MAP.willow,
	},
	[TREE_SHAPES.cypress]: {
		blobCount: 2,
		branchDepth: 0,
		branchesLevel1Range: [0, 0] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchMirroring: BRANCH_MIRRORING.off,
		trunkTwist: 20,
		blobSizeVariance: 1.0,
		blobCloseness: 80,
		canopyLightColor: '#2d5e3a',
		canopyDarkColor: '#0a2418',
		fruitType: SHAPE_FRUIT_MAP.cypress,
	},
	[TREE_SHAPES.apple]: {
		blobCount: 2,
		branchDepth: 1,
		branchesLevel1Range: [1, 2] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		blobCloseness: 70,
		canopyLightColor: '#6abf4b',
		trunkLightness: 30,
		fruitType: SHAPE_FRUIT_MAP.apple,
	},
	[TREE_SHAPES.cherry]: {
		blobCount: 4,
		branchesLevel1Range: [2, 4] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchAngle: 35,
		branchMirroring: BRANCH_MIRRORING.preferred,
		blobCloseness: 40,
		trunkSegments: 6,
		branchLength: 120,
		canopyLightColor: '#ffb7c5',
		canopyDarkColor: '#c4586a',
		trunkHue: 20,
		trunkSaturation: 40,
		fruitType: SHAPE_FRUIT_MAP.cherry,
		fruitCount: 4,
	},
	[TREE_SHAPES.bush]: {
		blobCount: 2,
		branchDepth: 0,
		branchesLevel1Range: [0, 0] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchMirroring: BRANCH_MIRRORING.off,
		trunkTwist: 30,
		blobCloseness: 60,
		canopyLightColor: '#3d8b50',
		fruitType: SHAPE_FRUIT_MAP.bush,
	},
	[TREE_SHAPES.baobab]: {
		blobCount: 3,
		branchDepth: 1,
		branchesLevel1Range: [2, 3] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchAngle: 40,
		trunkTwist: 40,
		blobSizeVariance: 1.5,
		blobCloseness: 60,
		trunkSegments: 5,
		branchLength: 60,
		branchLengthVariance: 30,
		canopyLightColor: '#7a9e6a',
		canopyDarkColor: '#3a5430',
		trunkHue: 30,
		trunkSaturation: 15,
		trunkLightness: 45,
		fruitType: SHAPE_FRUIT_MAP.baobab,
	},
	[TREE_SHAPES.acacia]: {
		blobCount: 3,
		branchDepth: 1,
		branchesLevel1Range: [2, 3] as readonly [number, number],
		branchesLevel2Range: [0, 0] as readonly [number, number],
		branchesLevel3Range: [0, 0] as readonly [number, number],
		branchAngle: 25,
		branchMirroring: BRANCH_MIRRORING.preferred,
		trunkFork: true,
		trunkTwist: 30,
		blobSizeVariance: 1.5,
		blobCloseness: 30,
		trunkSegments: 5,
		canopyLightColor: '#8ba858',
		canopyDarkColor: '#3d5028',
		trunkSaturation: 35,
		trunkLightness: 28,
		fruitType: SHAPE_FRUIT_MAP.acacia,
	},
} as const satisfies Record<Exclude<TreeShape, 'custom'>, ShapeDefaults>;
